name: Release Binaries

on:
  workflow_dispatch:
    inputs:
      ref:
        description: "Branch or tag to build."
        required: true
        type: string
      version:
        description: "Version to assign. Creates matching tag."
        required: true
        type: string

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest # we can cross-compile
    strategy:
      matrix:
        goos: ["darwin", "linux", "windows"]
        goarch: ["amd64", "arm64"]
        include:
          - goos: "darwin"
            binary_name: "mybin"
          - goos: "linux"
            binary_name: "mybin"
          - goos: "windows"
            binary_name: "mybin.exe"

    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ inputs.ref }}

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version-file: "./go.mod"

      - name: Build
        run: |
          go build -o ${{ matrix.binary_name }} .
        env:
          GOOS: ${{ matrix.goos }}
          GOARCH: ${{ matrix.goarch }}

      - name: Test
        run: |
          go test -v ./...

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: mybin-${{ matrix.goos }}-${{ matrix.goarch }}
          path: ${{ matrix.binary_name }}

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ inputs.ref }}

      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: ./artifacts

      - name: Set executable permissions
        run: |
          find artifacts -name "mybin*" -type f -exec chmod +x {} \;

      - name: Create zip archive with extra files
        run: |
          mv README.pypi.md README.md
          for artifact in artifacts/*; do
            platform=$(basename "$artifact")
            binary_file=$(find "$artifact" -name "mybin*" -type f)
            zip "${platform}-${{ inputs.version }}.zip" -j "$binary_file" README.md LICENSE
          done

      - name: Create Release
        run: |
          gh release create ${{ inputs.version }} \
            --title "Binary Release ${{ inputs.version }}" \
            --generate-notes \
            *.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
