name: Test Wheels

on:
  workflow_dispatch:
    inputs:
      package_name:
        description: "Package name on PyPI."
        required: true
        type: string
      version:
        description: "Package version to test."
        required: true
        type: string

jobs:
  test-wheels:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: macos-latest
            arch: amd64
          - os: macos-latest
            arch: arm64
          - os: ubuntu-latest
            arch: amd64
          - os: ubuntu-latest
            arch: arm64
          - os: windows-latest
            arch: amd64

    steps:
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Install package from Test PyPI
        run: |
          python -m pip install --upgrade pip
          pip install --index-url https://test.pypi.org/simple/ ${{ inputs.package_name }}==${{ inputs.version }}

      - name: Test binary exists and is executable (Unix-likes)
        if: matrix.os != 'windows-latest'
        run: |
          which mybin
          mybin --help

      - name: Test binary exists and is executable (Windows)
        if: matrix.os == 'windows-latest'
        run: |
          where mybin
          mybin.exe --help
